// Code generated by protoc-gen-go. DO NOT EDIT.
// source: marshal.proto

package marshal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PbStudent struct {
	Age                  int32    `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Salt                 float64  `protobuf:"fixed64,4,opt,name=salt,proto3" json:"salt,omitempty"`
	Sub                  *PbSub   `protobuf:"bytes,5,opt,name=sub,proto3" json:"sub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbStudent) Reset()         { *m = PbStudent{} }
func (m *PbStudent) String() string { return proto.CompactTextString(m) }
func (*PbStudent) ProtoMessage()    {}
func (*PbStudent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dada37257d85173, []int{0}
}

func (m *PbStudent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbStudent.Unmarshal(m, b)
}
func (m *PbStudent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbStudent.Marshal(b, m, deterministic)
}
func (m *PbStudent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbStudent.Merge(m, src)
}
func (m *PbStudent) XXX_Size() int {
	return xxx_messageInfo_PbStudent.Size(m)
}
func (m *PbStudent) XXX_DiscardUnknown() {
	xxx_messageInfo_PbStudent.DiscardUnknown(m)
}

var xxx_messageInfo_PbStudent proto.InternalMessageInfo

func (m *PbStudent) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PbStudent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PbStudent) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PbStudent) GetSalt() float64 {
	if m != nil {
		return m.Salt
	}
	return 0
}

func (m *PbStudent) GetSub() *PbSub {
	if m != nil {
		return m.Sub
	}
	return nil
}

type PbSub struct {
	// repeated bytes options = 1;
	Options              []byte   `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbSub) Reset()         { *m = PbSub{} }
func (m *PbSub) String() string { return proto.CompactTextString(m) }
func (*PbSub) ProtoMessage()    {}
func (*PbSub) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dada37257d85173, []int{1}
}

func (m *PbSub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbSub.Unmarshal(m, b)
}
func (m *PbSub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbSub.Marshal(b, m, deterministic)
}
func (m *PbSub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbSub.Merge(m, src)
}
func (m *PbSub) XXX_Size() int {
	return xxx_messageInfo_PbSub.Size(m)
}
func (m *PbSub) XXX_DiscardUnknown() {
	xxx_messageInfo_PbSub.DiscardUnknown(m)
}

var xxx_messageInfo_PbSub proto.InternalMessageInfo

func (m *PbSub) GetOptions() []byte {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*PbStudent)(nil), "pb_student")
	proto.RegisterType((*PbSub)(nil), "pb_sub")
}

func init() { proto.RegisterFile("marshal.proto", fileDescriptor_4dada37257d85173) }

var fileDescriptor_4dada37257d85173 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x4d, 0x0a, 0xc2, 0x30,
	0x10, 0x85, 0x19, 0xfb, 0x87, 0xa3, 0x82, 0x64, 0x35, 0xee, 0x42, 0x57, 0x59, 0x75, 0xa1, 0x37,
	0xc9, 0x05, 0x64, 0x42, 0x83, 0x0a, 0x6d, 0x53, 0x3a, 0xc9, 0xca, 0xcb, 0x4b, 0x22, 0xdd, 0x7d,
	0xdf, 0x63, 0x98, 0xf7, 0xf0, 0x32, 0xf3, 0x26, 0x6f, 0x9e, 0x86, 0x75, 0x0b, 0x31, 0xf4, 0x5f,
	0xc4, 0xd5, 0x3d, 0x25, 0xa6, 0xd1, 0x2f, 0x51, 0x5d, 0xb1, 0xe2, 0x97, 0x27, 0xd0, 0x60, 0x1a,
	0x9b, 0x51, 0x29, 0xac, 0x17, 0x9e, 0x3d, 0x1d, 0x34, 0x98, 0xa3, 0x2d, 0xac, 0x08, 0x3b, 0x1e,
	0xc7, 0xcd, 0x8b, 0x50, 0x55, 0xe2, 0x5d, 0xf3, 0xb5, 0xf0, 0x14, 0xa9, 0xd6, 0x60, 0xc0, 0x16,
	0x56, 0x37, 0xac, 0x24, 0x39, 0x6a, 0x34, 0x98, 0xd3, 0xbd, 0x1b, 0x72, 0x5b, 0x72, 0x36, 0x67,
	0x7d, 0x8f, 0xed, 0x5f, 0xf3, 0xcb, 0xb0, 0xc6, 0x4f, 0x58, 0xa4, 0x94, 0x9f, 0xed, 0xae, 0xae,
	0x2d, 0x3b, 0x1f, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x2c, 0x7d, 0x2e, 0xb8, 0x00, 0x00,
	0x00,
}
